source 'https://github.com/CocoaPods/Specs.git'

platform :osx, '10.13'

use_frameworks!

target 'Example-OSX' do
  pod "Concept2-SDK", :path => "../"
end

target 'Example-OSXTests' do
  pod "Concept2-SDK", :path => "../"
end
