source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!

target 'Example-iOS_Example' do
  pod "Concept2-SDK", :path => "../"
end

#target 'Example-iOS_Tests' do
#  pod "Concept2-SDK", :path => "../"
#end
